### ISSUE TITLE
DFGC 2021

### ISSUE THREAD

**Issue by erigamonte** [beibuwandeluori/DeeperForensicsChallengeSolution#2]
Hello, can you release the competition code of DFGC 2021? I am doing some researches about deepfake and it will be amazing if your solution is available like the DFGC 2020.

**Comment by beibuwandeluori** [comment]
Thanks for your suggestion. The code can be obtained in [`DFGC 1st Solution`](https://github.com/beibuwandeluori/DFGC_Detection),. Finally, looking forward to your start for our code.

**Comment by erigamonte** [comment]
thx
